version: 2.1
parameters:
  cacheVersion:
    default: "4-"
    description: "Update this value to clear the node_modules caches"
    type: string
  run_build_deploy:
    default: true
    type: boolean
  run_build_deploy_preview:
    default: false
    type: boolean
  ui_pull_number:
    default: ""
    type: string
  environment:
    default: staging
    type: string

cancel-previous-builds: &cancel-previous-builds
  working_directory: /tmp/workspace
  steps:
    - run:
        name: Cancel previous builds
        command: |
          ./.circleci/cancel-all-jobs.sh

deps: &deps
  working_directory: /tmp/workspace
  steps:
    - run:
        name: Install dependencies
        command: |
          for i in {1..50}; do
          echo "Installing dependency $i"
          sleep 2
          done
          echo "All done"
build: &build
  working_directory: /tmp/workspace
  steps:
    - run:
        name: Long running build task
        command: |
          for i in {1..50}; do
          echo "Build $i% complete"
          sleep 5
          done
          echo "All done"

jobs:
  cancel-previous-builds:
    <<: *cancel-previous-builds
  deps:
    <<: *deps
  build:
    <<: *build

workflows:
  build-deploy-preview:
    when: << pipeline.parameters.run_build_deploy_preview >>
    jobs:
      - cancel-previous-builds
      - deps
      - build

  build-deploy:
    when: << pipeline.parameters.run_build_deploy >>
    jobs:
      - cancel-previous-builds
      - deps
      - build
